### ISSUE TITLE
Calling setFlowAnimation() makes intro slides black with no content

### ISSUE THREAD

**Issue by peterhav** [apl-devs/AppIntro#466] opened 2017-07-23 09:36 UTC
I've switched from AppIntro version 4.2.0 to 4.2.1. This introduced several API breaks. Where can I find how to handle these?

Before: `implementation ('com.github.apl-devs:appintro:v4.2.0')`
Now using: `implementation ('com.github.apl-devs:appintro:v4.2.1')`

Examples of API breaks in this update are: 

```
AppIntroFragment.newInstance(
                "title",
               "description",
                R.drawable.tutorial1,
                ContextCompat.getColor(this, R.color.theme_accent)));
```

With 4.2.1 the above call does no longer work, a `SliderPage `should be passed as argument in the `newInstance `method, but when doing so the app intro only shows a black tab without contents.

I think it would be helpful to include some code examples that show how to convert to the new version easily.

**Comment by avluis** [comment] 2017-07-23 09:50
I'm still getting used to PR #428 myself -- `v4.2.1` was released because of a few request from the community ( #464 ) so documentation for said changes have not been written.

What I do know is that there is [example code](https://github.com/apl-devs/AppIntro/blob/master/example/src/main/java/com/amqtech/opensource/appintroexample/ui/mainTabs/intro/DefaultIntro.java#L23) --

Let me export a bit of that here:

```java
SliderPage sliderPage1 = new SliderPage();
sliderPage1.setTitle( "Welcome!" );
sliderPage1.setDescription( "This is a demo of the AppIntro library, with a custom background on each slide!" );
sliderPage1.setImageDrawable( R.drawable.ic_slide1 );
sliderPage1.setBgColor( Color.TRANSPARENT );
addSlide(AppIntroFragment.newInstance(sliderPage1));```

Essentially, you are building a `sliderPage` object instead of passing the arguments directly.

**Comment by peterhav** [comment] 2017-07-23 11:01
Thanks for the quick response. I did use this code as well, but the result is an empty, dark tab:

![appintro_after](https://user-images.githubusercontent.com/1724223/28498794-75a80bdc-6fa6-11e7-8b79-7c4b27e46bcd.png)

This is the tab as it was before (before introducing the SliderPage class as argument:

![appintro_before](https://user-images.githubusercontent.com/1724223/28498811-f884434a-6fa6-11e7-9934-9e331a7000d8.png)

Regarding improvements for the SliderPage class; in my opinion, the SliderPage should have a constructor (taking in the same arguments as the newInstance call before...).

**Comment by avluis** [comment] 2017-07-23 11:22
Thanks for taking the time to post those captures -- I'll be taking a second look at the class asap and either post proper usage or fix any issues it may have (I need to catch up on some sleep).

**Comment by avluis** [comment] 2017-07-23 17:44
@peterhav I ran the example project against a Pixel XL (on Android 8), a Nexus 6 (Android 7) and a LG G4 (on Android 6).
All of the devices above rendered the layout properly.

Are you able to post the code behind your slides? Maybe your usage reveals an unknown bug in the implementation.

**Comment by avluis** [comment] 2017-07-23 18:51
@peterhav I have reintroduced the old API for `AppIntroFragment` while making use of the new `SliderPage` model --- if you wish to test this against your code, simply change your JitPack dependency for AppIntro to point to the [SNAPSHOT](https://jitpack.io/#apl-devs/AppIntro/-SNAPSHOT) of the repo.

```gradle
	dependencies {
	        compile 'com.github.apl-devs:AppIntro:-SNAPSHOT'
	}
```

**Comment by peterhav** [comment] 2017-07-23 20:11
Hi @avluis, just found the cause of the issue: when I remove the call to `setFlowAnimation()` in my `AppIntro `Activity, the intro slides appear correct again (so there seems to be a bug there).

Regarding improving of the interface of the SliderPage class; I would at least add an annotation to the parameters as described here: [https://developer.android.com/studio/write/annotations.html](https://developer.android.com/studio/write/annotations.html)

At this moment, the code below will work fine in both situations, but the color will only be right in the second call.
```
p.setBgColor( R.color.theme_accent );
p.setBgColor( ContextCompat.getColor(this, R.color.theme_accent) );
```

Same for the to be drawable argument ( `@DrawableRes` ).

**Comment by avluis** [comment] 2017-07-23 20:26
Good to know that it is not the new class, but rather a bug somewhere else 🤣
I'll be taking a look at the animations to verify that they are working as intended.

As for improving `SliderPage` -- annotations were actually at the top of my list as well.

Quick question:
Did you try out the snapshot build?
I would like to know if your older code (where you are making the call to AppIntroFragment with all arguments, instead of using the SliderPage object) will work unchanged (of course, you will have the deprecated lint warning, but ignore that for testing).

**Comment by avluis** [comment] 2017-07-23 20:52
@peterhav As a side note:
Are you aware of an annotation that can force the use of ContextCompat?
If not, then an annotation will probably not be enough to restrict this.
Will probably need to peruse Stack for a bit to see if this has been asked~

**Comment by avluis** [comment] 2017-07-23 23:06
@peterhav I just tagged my latest commit with `v4.2.2` -- if you don't mind testing your animations once again under this.

**Comment by peterhav** [comment] 2017-07-24 19:29
Just verified that this is fixed in 4.2.2. Thanks for the quick action!

**Comment by peterhav** [comment] 2017-07-24 19:33
Also verified that the 'old' API is still compiling and running in the -SNAPSHOT release (I do see the deprecated annotations in my old code).

**Comment by avluis** [comment] 2017-07-29 10:56
@peterhav Is it ok to close this issue?

**Comment by peterhav** [comment] 2017-07-29 14:25
Yes, this solved the issue!

Op 29 jul. 2017 12:56 schreef "Luis E Alvarado" <notifications@github.com>:

**Closed** 2017-07-29 17:10 UTC
Labels: bug
