### ISSUE TITLE
Background not changing from black!

### ISSUE THREAD

**Issue by Kvaibhav01** [apl-devs/AppIntro#494] opened 2017-10-17 19:05 UTC
**AppIntro Version**: 4.2.2

**Device/Android Version**: Works great on every device. I use [Yu Yureka](https://www.gsmarena.com/yu_yureka-6987.php) as physical and Nexus 5X as emulated device for testing.

**Issue details**: The issue is that no matter what `android:background` property I add to my intro slides, **it always shows up in black color** which is nowhere used in my app code (I've checked the colors.xml file). In the code below I've used this method for my first three slides. But the _second method to add slides works perfectly_ (in which we set a title, description, background and image). Why is that so? And how can I fix it to add my own color? 

**Your Code**: slide_1.xml-

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorPrimary">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:textColor="#ffffff"
        android:textSize="54sp"
        android:gravity="center"
        android:text="This is Slide 1"/>


</LinearLayout>
```
colors.xml:-
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Primary color of the app (shown in the app bar) -->
    <color name="colorPrimary">#4d427a</color>

    <!-- Primary dark color of the app (shown in the status bar) -->
    <color name="colorPrimaryDark">#3e3469</color>

    <!-- Accent color of the app -->
    <color name="colorAccent">#d0706d</color>

    <!-- Text color for the details of the earthquake in the list item -->
    <color name="textColorEarthquakeDetails">#f07c55</color>

    <!-- Text color for the primary location of the earthquake in the list item -->
    <color name="textColorEarthquakeLocation">#3e3469</color>

    <!-- Color for an earthquake with magnitude 0 and 2 -->
    <color name="magnitude1">#4A7BA7</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 2 and 3 -->
    <color name="magnitude2">#04B4B3</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 3 and 4 -->
    <color name="magnitude3">#10CAC9</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 4 and 5 -->
    <color name="magnitude4">#F5A623</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 5 and 6 -->
    <color name="magnitude5">#FF7D50</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 6 and 7 -->
    <color name="magnitude6">#FC6644</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 7 and 8 -->
    <color name="magnitude7">#E75F40</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 8 and 9 -->
    <color name="magnitude8">#E13A20</color>

    <!-- Magnitude circle color for an earthquake with magnitude between 9 and 10 -->
    <color name="magnitude9">#D93218</color>

    <!-- Magnitude circle color for an earthquake with magnitude over 10 -->
    <color name="magnitude10plus">#C03823</color>
</resources>
```
IntroActivity.java:-
```
package com.example.android.quakereport;

import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;

import com.github.paolorotolo.appintro.AppIntro;
import com.github.paolorotolo.appintro.AppIntroFragment;

public class IntroActivity extends AppIntro {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(SampleSlide.newInstance(R.layout.slide_1));
        addSlide(SampleSlide.newInstance(R.layout.slide_2));
        addSlide(SampleSlide.newInstance(R.layout.slide_3));

        addSlide(AppIntroFragment.newInstance("Welcome", "This is a description", R.drawable.magnitude_circle, getColor(R.color.colorAccent)));

        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        showSkipButton(false);
        setDepthAnimation();

        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        finish();
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
    }
}
```
**Screenshots**:-

![Slide 1](https://i.imgur.com/EGSfj4M.png)
Slide 1 screenshot
![Slide 4](https://i.imgur.com/IPG5A5i.png)
Slide 4 screenshot

**Comment by avluis** [comment] 2017-10-17 21:08
Interesting -- have you tried defining it as a style? Something along the following:

**_theme.xml_**
```xml
    <!-- AppIntro Activity & Slides -->
    <style name="AppTheme.AppIntro" parent="AppTheme.DarkBackground">
        <item name="android:background">@color/primary_dark</item>
    </style>
```

**_slide_n.xml_**
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    ...
    style="@style/AppTheme.AppIntro"
    ...>
```

**Comment by gerardold** [comment] 2017-10-18 03:50
I have the same problem, I already tried with the styles and it does not work

**Comment by avluis** [comment] 2017-10-18 05:28
@gerardold I need you to show your code please -- don't want to miss anything.

**Comment by Kvaibhav01** [comment] 2017-10-18 18:42
Hi @avluis! I implemented the theme.xml and slide_n.xml code you provided but still it's the same. There's no effect.

**Comment by avluis** [comment] 2017-10-18 18:53
Well, unless I see more of your code, I'm not sure how else to help you as the library is not overriding anything from custom slides 🤷

**Comment by Kvaibhav01** [comment] 2017-10-18 19:23
Here are the links for each code (default) related to this library:

1. styles.xml:- https://gist.github.com/Kvaibhav01/7fef9f61591e449e46b162a852a95c50
2. strings.xml:- https://gist.github.com/Kvaibhav01/b68bfb544e0149861038cae87675a792
3. colors.xml:- https://gist.github.com/Kvaibhav01/bfae346079e425694eb1382182925f43
4. slide_1.xml:- https://gist.github.com/Kvaibhav01/a61ec8d92da1e1bf9a4eb663ff675719
5. SampleSlide.java:- https://gist.github.com/Kvaibhav01/e3d3828835940620bec4239d1bfec743
6. IntroActivity.java:- https://gist.github.com/Kvaibhav01/aa10124bc5b5c83ddad04afc2e5fce2f
7. App-level build.gradle:- https://gist.github.com/Kvaibhav01/d02a95a11acd29c9a08462cab734928b

**Comment by avluis** [comment] 2017-10-18 19:42
Thanks --- give me a bit to try and find the issue.

**Comment by avluis** [comment] 2017-10-18 20:02
@Kvaibhav01
Looks like the issue may simply be the way your custom fragments were created.

Can you delete `SampleSlide` and create `BaseSlide` with the following code:

```java
public class BaseSlide extends Fragment {

    private static final String ARG_LAYOUT_RES_ID = "layoutResId";
    private int layoutResId;

    public static BaseSlide newInstance(int layoutResId) {
        BaseSlide baseSlide = new BaseSlide();

        Bundle args = new Bundle();
        args.putInt(ARG_LAYOUT_RES_ID, layoutResId);
        baseSlide.setArguments(args);

        return baseSlide;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getArguments() != null && getArguments().containsKey(ARG_LAYOUT_RES_ID))
            layoutResId = getArguments().getInt(ARG_LAYOUT_RES_ID);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        return inflater.inflate(layoutResId, container, false);
    }
}
```

The issue is fairly simple -- the custom slide implementation can't find the layout(s) needed in your custom fragment if they don't implement something similar to the above.
Let me know if this resolves the issue for you.

**Comment by Kvaibhav01** [comment] 2017-10-20 13:46
I deleted the SampleSlide.java file, added a new BaseSlide.java and added the code given above.
Next, I changed SampleSlide to BaseSlide in the IntroActivity.java file as:

```
// Add your slide fragments here.
// AppIntro will automatically generate the dots indicator and buttons.
addSlide(BaseSlide.newInstance(R.layout.slide_1));
addSlide(BaseSlide.newInstance(R.layout.slide_2));
addSlide(BaseSlide.newInstance(R.layout.slide_3));
```
But I get errors in these three lines of code! The error is: _incompatible types: BaseSlide cannot be converted to Fragment_. How do I resolve it now?

**Comment by avluis** [comment] 2017-10-20 14:20
Make sure you are importing the Support Library version of the Fragment class.
If you delete your current imports for the Fragment library, you should be able to re-import once again.

**Comment by avluis** [comment] 2017-10-20 14:26
⛔️
![No Good!](https://user-images.githubusercontent.com/875593/31825646-82e5882a-b578-11e7-8fdc-11693f226be0.png)

✔️
![Good!](https://user-images.githubusercontent.com/875593/31825650-84e6f348-b578-11e7-8b71-10dbc22e77a0.png)

**Comment by Kvaibhav01** [comment] 2017-10-20 14:30
That import has already been added to the file 😞 

![Alt text](https://i.imgur.com/0v6FOvN.png)

**Comment by avluis** [comment] 2017-10-20 15:08
`BaseSlide` and `IntroActivity`?

**Comment by Kvaibhav01** [comment] 2017-10-20 17:56
Thanks a ton! That solved the issue. 😄 I had `import android.app.Fragment;` instead of `import android.support.v4.app.Fragment;` in BaseSlide.java.

**Comment by avluis** [comment] 2017-10-20 22:41
Neat -- closing this for now

**Closed by avluis** 2017-10-20 22:41 UTC

**Comment by softmarshmallow** [comment] 2019-02-16 20:42
> Here are the links for each code (default) related to this library:
> 
> 1. styles.xml:- https://gist.github.com/Kvaibhav01/7fef9f61591e449e46b162a852a95c50
> 2. strings.xml:- https://gist.github.com/Kvaibhav01/b68bfb544e0149861038cae87675a792
> 3. colors.xml:- https://gist.github.com/Kvaibhav01/bfae346079e425694eb1382182925f43
> 4. slide_1.xml:- https://gist.github.com/Kvaibhav01/a61ec8d92da1e1bf9a4eb663ff675719
> 5. SampleSlide.java:- https://gist.github.com/Kvaibhav01/e3d3828835940620bec4239d1bfec743
> 6. IntroActivity.java:- https://gist.github.com/Kvaibhav01/aa10124bc5b5c83ddad04afc2e5fce2f
> 7. App-level build.gradle:- https://gist.github.com/Kvaibhav01/d02a95a11acd29c9a08462cab734928b

Link is Dead.

**Comment by Kvaibhav01** [comment] 2019-02-17 08:25
Yes @softmarshmallow I deleted them because my issue was solved :)
