### ISSUE TITLE
Where is model/SliderPage.java in  'com.github.apl-devs:appintro:v4.2.0'

### ISSUE THREAD

**Issue by NLLAPPS** [apl-devs/AppIntro#464] opened 2017-07-17 13:51 UTC
Hi, am I missing something? There is no model/SliderPage.java in  'com.github.apl-devs:appintro:v4.2.0'

**Comment by RahulSDeshpande** [comment] 2017-07-21 19:53
Right..
I am too tricked by this thing !!

I couldn't find anywhere..

**Comment by avluis** [comment] 2017-07-21 20:17
https://github.com/apl-devs/AppIntro/blob/master/library/src/main/java/com/github/paolorotolo/appintro/model/SliderPage.java

**Comment by NLLAPPS** [comment] 2017-07-21 20:23
It is not in the repo version when you add it to your gradle.build file

**Comment by avluis** [comment] 2017-07-21 20:26
Are you following the new repo instructions (with JitPack)?

**Comment by NLLAPPS** [comment] 2017-07-21 20:33
Yes, from your read me

**Comment by avluis** [comment] 2017-07-21 20:41
Have you tried cleaning and re-building the project?
![capture](https://user-images.githubusercontent.com/875593/28481547-012bd53a-6e2b-11e7-9b88-42ce71c2c2f0.PNG)

**Comment by RahulSDeshpande** [comment] 2017-07-22 07:07
@avluis, you are importing the dependencies locally as we can see in your screenshot, which might work properly as your library project is having the package **/model**.
If we try importing AppIntro lib from the JitPack, the **/model** package seems to be missing.
That is the reason **SliderPage.java** class is not found in this case for some reason :)

Plz check below screenshot of my Android Studio project.

![appintroissuescreenshot1](https://user-images.githubusercontent.com/6327731/28489187-23c8ff46-6eda-11e7-96ba-9fff830ef8eb.PNG)

Seems JitPack build has missed the **/model** package in its JAR building process.

**Comment by avluis** [comment] 2017-07-22 07:15
@RahulSDeshpande Cool -- I can work with this comment as you are giving me enough info to go out and figure out what's the issue.
And yes, since I work on the library, my dependencies would be local.
Let me see if there is anything that I can do to have JitPack grab the complete library.

**Comment by avluis** [comment] 2017-07-22 07:21
@RahulSDeshpande Can you do me a favor and modify your import from the general instructions to the following:

```gradle
	dependencies {
	        compile 'com.github.apl-devs:AppIntro:-SNAPSHOT'
	}
```

**Comment by RahulSDeshpande** [comment] 2017-07-22 08:46
Cool..
Glad to get your quick reply !!
Just give me 10mins, will reply !!

:)

**Comment by RahulSDeshpande** [comment] 2017-07-22 09:36
@avluis BINGO !!
It worked !!
Lets create **4.2.1** :)

Though the example given in the repo is showing me **blank pages** for all the tabs in the viewPager.
Also have noticed the same for the template 2 & 3.
Anyways, will append this issue in the ongoing issue #440.

Anyways plz confirm & lets close this issue.

:)

**Comment by avluis** [comment] 2017-07-22 14:39
@RahulSDeshpande The examples not displaying is an issue I'll be tacking in a bit #442 -- I didn't have a device on hand to reproduce, but I do now so I'm hoping that will be `4.2.2`.

As for the templates, can you clarify that for me -- or opening an issue (or appending to an existing issue where relevant)?

---
Anyways, I'm proceeding with releasing `4.2.1` in order to finally close this issue.

**Closed** 2017-07-22 15:02 UTC

**Comment by RahulSDeshpande** [comment] 2017-07-22 15:44
@avluis Cool thanks..

And yes, will do it as soon as I find the root cause :)

Will create a PR for it if I am able to fix all at once :)
